//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoXappia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El puerto serie COM1 no se encontro.")]
        public string portNotFound {
            get {
                return ((string)(this["portNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fingerprint Sensor has not been connected ")]
        public string fingerPrintNotFound {
            get {
                return ((string)(this["fingerPrintNotFound"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The loading of the fingerprint identification driver failed ")]
        public string driverNotFound {
            get {
                return ((string)(this["driverNotFound"]));
            }
            set {
                this["driverNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int numberPort {
            get {
                return ((int)(this["numberPort"]));
            }
            set {
                this["numberPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user=root;database=projectoHuellas;port=3306;password=;")]
        public string conectionString {
            get {
                return ((string)(this["conectionString"]));
            }
            set {
                this["conectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM `cliente` where DNI=")]
        public string queryTraerUnCliente {
            get {
                return ((string)(this["queryTraerUnCliente"]));
            }
            set {
                this["queryTraerUnCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM `cliente`")]
        public string queryTraerTodosLosClientes {
            get {
                return ((string)(this["queryTraerTodosLosClientes"]));
            }
            set {
                this["queryTraerTodosLosClientes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE `cliente` SET `Huella` = @huella WHERE `cliente`.`ClienteKey` = @key")]
        public string querySetiarHuellaCliente {
            get {
                return ((string)(this["querySetiarHuellaCliente"]));
            }
            set {
                this["querySetiarHuellaCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuario no registrado.")]
        public string usuarioInvalido {
            get {
                return ((string)(this["usuarioInvalido"]));
            }
            set {
                this["usuarioInvalido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Registro exitoso !")]
        public string enrollSucces {
            get {
                return ((string)(this["enrollSucces"]));
            }
            set {
                this["enrollSucces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No existe el dni en la Base")]
        public string usuarioNoHallado {
            get {
                return ((string)(this["usuarioNoHallado"]));
            }
            set {
                this["usuarioNoHallado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se pudo conectar a la base de datos, checke el conection string .")]
        public string DBError {
            get {
                return ((string)(this["DBError"]));
            }
            set {
                this["DBError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02 64 89 83 32 03 5D")]
        public string HexaAbrirMolinete {
            get {
                return ((string)(this["HexaAbrirMolinete"]));
            }
            set {
                this["HexaAbrirMolinete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("token?grant_type=password&client_id=3MVG9jfQT7vUue.GEc7ivydwM517vPOwaDZo85TO3rxES" +
            "iOpw9ax1hy1CVThAFi80tKXodY_7YEeTxPNpmgNR&client_secret=2465685332049427962&usern" +
            "ame=openpark@xappia.com.dev&password=saasy2511BaBVzVa6K4R6saJnw6bgwnDcj")]
        public string dataSalesforceWsAuthentication {
            get {
                return ((string)(this["dataSalesforceWsAuthentication"]));
            }
            set {
                this["dataSalesforceWsAuthentication"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test.salesforce.com/services/oauth2/")]
        public string salesforceUrlToken {
            get {
                return ((string)(this["salesforceUrlToken"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Algo va mal con el servicio de salesforce, intentelo denuevo más tarde.")]
        public string salesforceError {
            get {
                return ((string)(this["salesforceError"]));
            }
            set {
                this["salesforceError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02 64 89 80 03 6C")]
        public string hexaAvvesoRechazado {
            get {
                return ((string)(this["hexaAvvesoRechazado"]));
            }
            set {
                this["hexaAvvesoRechazado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nombre")]
        public string ColumnaNombre {
            get {
                return ((string)(this["ColumnaNombre"]));
            }
            set {
                this["ColumnaNombre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DNI")]
        public string ColumnaDNI {
            get {
                return ((string)(this["ColumnaDNI"]));
            }
            set {
                this["ColumnaDNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apellido")]
        public string ColumnaApellido {
            get {
                return ((string)(this["ColumnaApellido"]));
            }
            set {
                this["ColumnaApellido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PuedePasar")]
        public string ColumnaPuedepasar {
            get {
                return ((string)(this["ColumnaPuedepasar"]));
            }
            set {
                this["ColumnaPuedepasar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error al actualizar la base de datos con el nuevo registro. El registro de huella" +
            " fue exitoso en salesforce.")]
        public string localDataBaseError {
            get {
                return ((string)(this["localDataBaseError"]));
            }
            set {
                this["localDataBaseError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hubo un problema al autenticar, no hallamos registro de su usuario.")]
        public string usuarioInexistente {
            get {
                return ((string)(this["usuarioInexistente"]));
            }
            set {
                this["usuarioInexistente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO `ingresos` (`ID`, `DNI`, `Fecha`) VALUES (NULL, @dni, @fecha);")]
        public string querySetiarLog {
            get {
                return ((string)(this["querySetiarLog"]));
            }
            set {
                this["querySetiarLog"] = value;
            }
        }
    }
}
